[project]
name = "ejercicios_individualesmodulo3"
version = "0.1.0"
description = "Ejercicios Individuales del MÃ³dulo 3 -  Mayerly Cardenas"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
